config/routes.rb
Rails.application.routes.draw do
  resources :notices
  resources :meetings
  resources :bookings

  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'notices#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy!

    respond_to do |format|
      format.html { redirect_to bookings_path, status: :see_other, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:place, :requester, :day, :begin, :end)
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[show edit update destroy]

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1 or /meetings/1.json
  def show; end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit; end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy!

    respond_to do |format|
      format.html { redirect_to meetings_path, status: :see_other, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def meeting_params
    params.require(:meeting).permit(:title, :content, :day, :begin, :end, :created_by)
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: %i[show edit update destroy]

  # GET /notices or /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1 or /notices/1.json
  def show; end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit; end

  # POST /notices or /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1 or /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1 or /notices/1.json
  def destroy
    @notice.destroy!

    respond_to do |format|
      format.html { redirect_to notices_path, status: :see_other, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_notice
    @notice = Notice.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def notice_params
    params.require(:notice).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>Place:</strong>
    <%= booking.place %>
  </p>

  <p>
    <strong>Requester:</strong>
    <%= booking.requester %>
  </p>

  <p>
    <strong>Day:</strong>
    <%= booking.day %>
  </p>

  <p>
    <strong>Begin:</strong>
    <%= booking.begin %>
  </p>

  <p>
    <strong>End:</strong>
    <%= booking.end %>
  </p>

</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="sm:col-span-4">
      <%= form.label :place, "Lugar", class: "block text-sm font-medium leading-6 text-gray-900" %>
      <div class="mt-2">
        <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
          <%= form.text_field :place, class: "block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" %>
        </div>
      </div>
    </div>

    <div class="sm:col-span-4">
      <%= form.label :requester, "Nome", class: "block text-sm font-medium leading-6 text-gray-900" %>
      <div class="mt-2">
        <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
          <%= form.text_field :requester, class: "block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" %>
        </div>
    </div>

    <div class="flex gap-5 items-center mt-5">
      <div>
        <%= form.label :day, "Dia" %>
        <div class="flex">
          <%= form.date_field :day %>
        </div>
      </div>

      <div class="max-w-[8.5rem] mx-auto">
        <%= form.label :begin, "Início",class: "block mb-2 text-sm font-medium text-gray-900" %>
        <div class="flex">
          <%= form.time_field :begin, class: "rounded-none rounded-s-lg bg-gray-50 border text-gray-900 leading-none focus:ring-blue-500 focus:border-blue-500 block flex-1 w-full text-sm border-gray-300 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
          <span class="inline-flex items-center px-3 text-sm text-gray-900 bg-gray-200 border rounded-s-0 border-s-0 border-gray-300 rounded-e-md dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600">
            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
              <path fill-rule="evenodd" d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12Zm11-4a1 1 0 1 0-2 0v4a1 1 0 0 0 .293.707l3 3a1 1 0 0 0 1.414-1.414L13 11.586V8Z" clip-rule="evenodd"/>
            </svg>
          </span>
        </div>
      </div>

      <div class="max-w-[8.5rem] mx-auto">
        <%= form.label :end, "Fim",class: "block mb-2 text-sm font-medium text-gray-900" %>
        <div class="flex">
          <%= form.time_field :end, class: "rounded-none rounded-s-lg bg-gray-50 border text-gray-900 leading-none focus:ring-blue-500 focus:border-blue-500 block flex-1 w-full text-sm border-gray-300 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
          <span class="inline-flex items-center px-3 text-sm text-gray-900 bg-gray-200 border rounded-s-0 border-s-0 border-gray-300 rounded-e-md dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600">
            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
              <path fill-rule="evenodd" d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12Zm11-4a1 1 0 1 0-2 0v4a1 1 0 0 0 .293.707l3 3a1 1 0 0 0 1.414-1.414L13 11.586V8Z" clip-rule="evenodd"/>
            </svg>
          </span>
        </div>
      </div>
    </div>

  <div class="mt-6 flex items-center gap-x-6">
    <button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
      Salvar
    </button>
    <%= link_to "Voltar", bookings_path, :class => "text-sm font-semibold leading-6 text-gray-900" %>
  <div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<div class="min-h-full">
  <nav class="bg-gray-800">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="flex h-16 items-center justify-between">
        <div class="flex items-center">
          <div class="flex-shrink-0">
            <img class="h-8 w-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
          </div>
          <div class="hidden md:block">
            <div class="ml-10 flex items-baseline space-x-4">
              <a href="/notices" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white" aria-current="page">Avisos</a>
              <a href="/bookings" class="rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white">Reservas</a>
              <a href="/meetings" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Encontros</a>
            </div>
          </div>
        </div>
        <div class="hidden md:block">
          <div class="ml-4 flex items-center md:ml-6">
            <button type="button" class="relative rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
              <span class="absolute -inset-1.5"></span>
              <span class="sr-only">View notifications</span>
              <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">Reservas</h1>
    </div>
  </header>
  <main>
    <div class="flex justify-center mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
    <table class="w-2/3">
      <thead>
          <tr class="flex justify-between px-3">
            <th class="text-xl">Lugar</th>
            <th class="text-xl">Solicitante</th>
            <th class="text-xl">Data</th>
            <th class="text-xl">Hora</th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.each do |b| %>
          <tr class="flex justify-between px-3 border-b p-3 hover:bg-zinc-50">
            <td><%= b[:place] %></td>
            <td><%= b[:requester] %></td>
            <td><%= b[:day].strftime("%m/%d") %></td>
            <td><%= b[:begin].strftime("%H:%M") %> até <%= b[:end].strftime("%H:%M") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
     <%= link_to "+", new_booking_path, :class => "flex justify-center border rounded-full p-5 w-16 font-semibold
        fixed bottom-10 right-20 bg-blue-500 hover:bg-blue-400" %>
    </div>
  </main>
</div>

app/views/bookings/new.html.erb
<div class="w-screen flex justify-center">
  <div class="flex flex-col rounded-lg w-1/3 items-center border-2 mt-24 p-5 gap-5">
    <h1 class="font-bold">Nova Reserva</h1>

    <%= render "form", booking: @booking %>
  </div>
<div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @booking %>

<div>
  <%= link_to "Edit this booking", edit_booking_path(@booking) %> |
  <%= link_to "Back to bookings", bookings_path %>

  <%= button_to "Destroy this booking", @booking, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-100">
  <head>
    <title>Neighborly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-full">
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/meetings/_meeting.html.erb
<div id="<%= dom_id meeting %>" class="border-2 rounded-xl p-5">
  <h1 class="text-3xl font-bold mb-5"><%= meeting.title.upcase %></h1>

  <p class="mb-5"><%= meeting.content %></p>

  <p>
    <strong>Dia:</strong>
    <%= meeting.day.strftime("%d/%m") %>
  </p>

  <p class="mb-5">
    <strong>Horário:</strong>
    <%= meeting.begin.strftime("%H:%M") %> até <%= meeting.end.strftime("%H:%M") %> 
  </p>

  <p>Postado em: <strong><%= meeting.created_at.strftime("%d/%m/%Y") %> às <%= meeting.created_at.strftime("%H:%M") %></strong></p>
</div>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render "form", meeting: @meeting %>

<br>

<div>
  <%= link_to "Show this meeting", @meeting %> |
  <%= link_to "Back to meetings", meetings_path %>
</div>

app/views/meetings/index.html.erb
<div class="min-h-full">
  <nav class="bg-gray-800">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="flex h-16 items-center justify-between">
        <div class="flex items-center">
          <div class="flex-shrink-0">
            <img class="h-8 w-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
          </div>
          <div class="hidden md:block">
            <div class="ml-10 flex items-baseline space-x-4">
              <a href="/notices" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Avisos</a>
              <a href="/bookings" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Reservas</a>
              <a href="/meetings" class="rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" aria-current="page">Encontros</a>
            </div>
          </div>
        </div>
        <div class="hidden md:block">
          <div class="ml-4 flex items-center md:ml-6">
            <button type="button" class="relative rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
              <span class="absolute -inset-1.5"></span>
              <span class="sr-only">View notifications</span>
              <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">Encontros</h1>
    </div>
  </header>
  <main>
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <% @meetings.each do |meeting| %>
        <div class="border-2 p-5 rounded-xl mb-5 hover:bg-gray-200">
          <a href="/meetings/<%= meeting.id %>">
            <h1 class="font-bold pb-2"><%= meeting.title.upcase %></h1>
            <p class="italic text-sm pb-5"><%= meeting.created_by %></p>
            <p><%= meeting.content %></p>
            <p class="text-right">Postado em: <strong><%= meeting.created_at.strftime("%d/%m/%Y") %> às <%= meeting.created_at.strftime("%H:%M") %></strong></p>
          </a>
       </div>
     <% end %>
     <%= link_to "+", new_meeting_path, :class => "flex justify-center border rounded-full p-5 w-16 font-semibold
        fixed bottom-10 right-20 bg-blue-500 hover:bg-blue-400" %>
    </div>
  </main>
</div>

app/views/meetings/new.html.erb
<div class="w-screen flex justify-center">
  <div class="flex flex-col rounded-lg w-1/3 items-center border-2 mt-24 p-5 gap-5">
    <h1 class="font-bold">Novo Encontro</h1>

    <%= render "form", meeting: @meeting %>
  </div>
<div>

app/views/meetings/show.html.erb
<div class="w-screen h-screen flex flex-col items-center mt-40">
  <p style="color: green"><%= notice %></p>

  <%= render @meeting %>

  <div class="mt-12">
    <%= link_to "Voltar", meetings_path, :class => "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
  </div>
</div>

app/views/notices/_form.html.erb
<%= form_with(model: notice) do |form| %>
  <% if notice.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
        <% notice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="sm:col-span-4">
      <%= form.label :title, "Título", class: "block text-sm font-medium leading-6 text-gray-900" %>
      <div class="mt-2">
        <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
          <%= form.text_field :title, class: "block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class="sm:col-span-4">
        <%= form.label :content, "Assunto:", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
            <%= form.text_area :content, class: "block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" %>
      </div>
    </div>

  <div class="mt-6 flex items-center justify-end gap-x-6">
    <button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
      Salvar
    </button>
    <%= link_to "Voltar", notices_path, :class => "text-sm font-semibold leading-6 text-gray-900" %>
  <div>
<% end %>

app/views/notices/_notice.html.erb
<div id="<%= dom_id notice %>" class="flex flex-col items-center border-2 rounded-xl w-1/3 h-1/3 justify-between p-5">
  <h1 class="text-3xl font-bold mb-5"><%= notice.title.upcase %></h1>

  <p><%= notice.content %></p>

  <p>Postado em: <strong><%= notice.created_at.strftime("%d/%m/%Y") %> às <%= notice.created_at.strftime("%H:%M") %></strong></p>
</div>

app/views/notices/index.html.erb
<div class="min-h-full">
  <nav class="bg-gray-800">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="flex h-16 items-center justify-between">
        <div class="flex items-center">
          <div class="flex-shrink-0">
            <img class="h-8 w-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
          </div>
          <div class="hidden md:block">
            <div class="ml-10 flex items-baseline space-x-4">
              <a href="/notices" class="rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" aria-current="page">Avisos</a>
              <a href="/bookings" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Reservas</a>
              <a href="/meetings" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Encontros</a>
            </div>
          </div>
        </div>
        <div class="hidden md:block">
          <div class="ml-4 flex items-center md:ml-6">
            <button type="button" class="relative rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
              <span class="absolute -inset-1.5"></span>
              <span class="sr-only">View notifications</span>
              <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">Avisos</h1>
    </div>
  </header>
  <main>
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <% @notices.each do |notice| %>
        <div class="border-2 p-5 rounded-xl mb-5 hover:bg-gray-200">
          <a href="/notices/<%= notice.id %>">
            <h1 class="font-bold pb-5"><%= notice.title.upcase %></h1>
            <p><%= notice.content %></p>
            <p class="text-right">Postado em: <strong><%= notice.created_at.strftime("%d/%m/%Y") %> às <%= notice.created_at.strftime("%H:%M") %></strong></p>
          </a>
       </div>
     <% end %>
     <%= link_to "+", new_notice_path, :class => "flex justify-center border rounded-full p-5 w-16 font-semibold
        fixed bottom-10 right-20 bg-blue-500 hover:bg-blue-400" %>
    </div>
  </main>
</div>